spawn(function()
        loadstring(game:HttpGet(
            "https://raw.githubusercontent.com/vinh129150/hack/refs/heads/main/Notify.lua"
        ))()
    end)
spawn(function()
        loadstring(game:HttpGet(
            "https://raw.githubusercontent.com/trungdao2k4/trauroblox/refs/heads/main/concac.lua"
        ))()
    end)
